site_name: 'A Public Wiki'
site_url: https://nwest.wiki
repo_url: https://github.com/nwesterhausen/public-wiki
edit_uri: edit/main/docs
site_author: Nicholas Westerhausen
copyright: ©2023 Nick Westerhausen
theme:
  name: 'lantana'
plugins:
  - search
  - minify:
      minify_html: true
